<script setup lang="ts">
import { FileDown, FilePlus2, RefreshCw } from 'lucide-vue-next'
import type { Crop, CropCycle, Station } from '~/types/api'
useSeoMeta({title:'Reportes'}); const {request}=useApi(); const stations=ref<Station[]>([]); const crops=ref<Crop[]>([]); const cycles=ref<CropCycle[]>([]); const reports=ref<any[]>([]); const form=reactive({station_id:'',crop_code:'SOJA',cycle_id:'',date_from:new Date(Date.now()-7*86400000).toISOString().slice(0,10),date_to:new Date().toISOString().slice(0,10)}); const creating=ref(false); const message=ref('')
async function load(){[stations.value,crops.value,reports.value]=await Promise.all([request('/public/stations'),request('/public/crops'),request('/reports/public',{query:{limit:30}})]);if(!form.station_id&&stations.value[0])form.station_id=stations.value[0].id;await loadCycles()}
async function loadCycles(){cycles.value=form.station_id?await request('/public/crop-cycles',{query:{station_id:form.station_id,crop_code:form.crop_code}}):[];if(!cycles.value.some(x=>x.id===form.cycle_id))form.cycle_id=''}
async function createReport(){creating.value=true;message.value='';try{const result:any=await request('/reports',{method:'POST',body:form});message.value=`Reporte ${result.status}. Puede actualizar la lista para consultar su avance.`;await load()}finally{creating.value=false}}
watch(()=>[form.station_id,form.crop_code],loadCycles); onMounted(load)
</script>
<template><div class="page"><div class="container"><h1 class="page-title">Reportes agrometeorológicos</h1><p class="page-subtitle">Genere un documento PDF por rango de fechas con datos, alertas, fenología, gráficos y metodología.</p><form class="card report-form" @submit.prevent="createReport"><div class="card-body form-grid"><label><span class="label">Estación</span><select v-model="form.station_id" class="select" required><option v-for="s in stations" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label><span class="label">Cultivo</span><select v-model="form.crop_code" class="select"><option v-for="c in crops" :key="c.id" :value="c.code">{{c.name}}</option></select></label><label><span class="label">Ciclo productivo</span><select v-model="form.cycle_id" class="select"><option value="">Sin ciclo específico</option><option v-for="c in cycles" :key="c.id" :value="c.id">{{c.name}}</option></select></label><div/><label><span class="label">Fecha desde</span><input v-model="form.date_from" class="input" type="date" required></label><label><span class="label">Fecha hasta</span><input v-model="form.date_to" class="input" type="date" required></label></div><div class="report-actions"><button class="btn btn-primary" :disabled="creating"><FilePlus2/>{{creating?'Creando trabajo…':'Generar reporte'}}</button></div></form><p v-if="message" class="notice">{{message}}</p><section class="history"><div class="row-between"><h2 class="section-title">Historial</h2><button class="btn btn-light" @click="load"><RefreshCw/>Actualizar</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Creado</th><th>Estación</th><th>Cultivo</th><th>Periodo</th><th>Estado</th><th>Archivo</th></tr></thead><tbody><tr v-for="r in reports" :key="r.id"><td>{{new Date(r.created_at).toLocaleString('es-PY')}}</td><td>{{r.station_name}}</td><td>{{r.crop_name}}</td><td>{{r.date_from}} – {{r.date_to}}</td><td><span class="badge" :class="r.status==='COMPLETED'?'badge-success':r.status==='FAILED'?'badge-danger':'badge-warning'">{{r.status}}</span></td><td><NuxtLink v-if="r.status==='COMPLETED'" class="btn btn-light" :to="`/fecoclima-ia/reportes/${r.id}`"><FileDown/>Abrir</NuxtLink><span v-else>—</span></td></tr><tr v-if="!reports.length"><td colspan="6"><EmptyState title="Sin reportes"/></td></tr></tbody></table></div></div></section></div></div></template>
<style scoped>.report-form{margin-top:24px}.report-actions{padding:0 22px 22px;display:flex;justify-content:flex-end}.btn svg{width:18px}.history{margin-top:30px}</style>
