<script setup lang="ts">
import { Search, RotateCcw, Sprout } from 'lucide-vue-next'
import type { Crop, Station } from '~/types/api'
useSeoMeta({ title:'Fenología' }); const {request}=useApi(); const stations=ref<Station[]>([]); const crops=ref<Crop[]>([]); const form=reactive({station_id:'',crop_code:'SOJA',sowing_type:'directa',cycle_type:'normal',planting_date:new Date().toISOString().slice(0,10),requirement:'etapa_actual'}); const result=ref<any>(null); const loading=ref(false); const error=ref('')
onMounted(async()=>{[stations.value,crops.value]=await Promise.all([request('/public/stations'),request('/public/crops')]);if(stations.value[0])form.station_id=stations.value[0].id})
async function calculate(){loading.value=true;error.value='';try{result.value=await request('/phenology/calculate',{method:'POST',body:form})}catch(e:any){error.value=e?.data?.detail||'No se pudo calcular'}finally{loading.value=false}}
function reset(){form.station_id=stations.value[0]?.id||'';form.crop_code='SOJA';form.sowing_type='directa';form.cycle_type='normal';form.planting_date=new Date().toISOString().slice(0,10);form.requirement='etapa_actual';result.value=null}
</script>
<template><div class="page phenology-page"><div class="container"><div class="phenology-title"><Sprout/><h1 class="page-title">Fenología</h1><p class="page-subtitle">Monitoreo fenológico y climático en cultivos</p></div><form class="phenology-form card" @submit.prevent="calculate"><div class="card-body form-grid"><label><span class="label">Estación</span><select v-model="form.station_id" class="select" required><option value="">Seleccione un elemento</option><option v-for="s in stations" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label><span class="label">Cultivo</span><select v-model="form.crop_code" class="select"><option v-for="c in crops" :key="c.id" :value="c.code">{{c.name}}</option></select></label><label><span class="label">Tipo de siembra</span><select v-model="form.sowing_type" class="select"><option value="directa">Siembra directa</option><option value="convencional">Convencional</option><option value="trasplante">Trasplante</option></select></label><label><span class="label">Tipo de ciclo</span><select v-model="form.cycle_type" class="select"><option value="corto">Corto</option><option value="normal">Normal</option><option value="largo">Largo</option></select></label><label><span class="label">Requerimiento</span><select v-model="form.requirement" class="select"><option value="etapa_actual">Etapa actual</option><option value="calendario">Calendario completo</option><option value="riesgos">Riesgos por etapa</option></select></label><label><span class="label">Fecha de siembra</span><input v-model="form.planting_date" class="input" type="date" required></label></div><div class="actions"><button type="submit" class="btn btn-secondary" :disabled="loading"><Search/>{{loading?'Calculando…':'Buscar'}}</button><button type="button" class="btn btn-primary" @click="reset"><RotateCcw/>Limpiar filtros</button></div></form><ErrorState v-if="error" :message="error" @retry="calculate"/><section v-if="result" class="result card"><div class="card-body"><div class="row-between"><div><span class="badge badge-info">Día {{result.days_after_planting}}</span><h2>{{result.stage_name}}</h2><p>{{result.description}}</p></div><div class="stage-code">{{result.stage_code}}</div></div><hr class="divider"><h3>Calendario estimado</h3><div class="timeline"><div v-for="stage in result.timeline" :key="stage.code" class="timeline-item" :class="{active:stage.code===result.stage_code}"><b>{{stage.code}}</b><span>{{stage.name}}</span><small>Días {{stage.start_day}}–{{stage.end_day}}</small></div></div><p class="notice notice-warning small">La etapa es una estimación por días acumulados. Puede corregirse manualmente en el ciclo productivo con observación de campo.</p></div></section></div></div></template>
<style scoped>.phenology-page{background:linear-gradient(#fff 0,#eef7fc 45%,var(--fc-bg) 100%)}.phenology-title{text-align:center;margin-bottom:18px}.phenology-title>svg{width:52px;height:52px;color:var(--fc-primary)}.phenology-form{max-width:1100px;margin:0 auto}.actions{display:flex;justify-content:center;gap:6px;padding:0 22px 22px}.actions svg{width:18px}.result{max-width:1100px;margin:25px auto 0}.result h2{margin:10px 0 5px;color:var(--fc-primary)}.result p{color:var(--fc-text-muted)}.stage-code{width:90px;height:90px;display:grid;place-items:center;border-radius:50%;background:var(--fc-primary);color:#fff;font-size:1.7rem;font-weight:900}.timeline{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px;margin:15px 0 20px}.timeline-item{padding:13px;border:1px solid var(--fc-border);border-radius:10px;background:var(--fc-surface-muted)}.timeline-item.active{color:#fff;background:var(--fc-primary);border-color:var(--fc-primary)}.timeline-item b,.timeline-item span,.timeline-item small{display:block}.timeline-item span{margin:4px 0;font-size:.84rem}.timeline-item small{opacity:.75}@media(max-width:650px){.actions{flex-direction:column}.actions .btn{width:100%}.stage-code{width:70px;height:70px}}</style>
